library(dscr)
setwd('~/Desktop/BlackJack/BlackJack/dscr-template/')
#source("scenarios.R")
#source("methods.R")
#source("score.R")
dsc_blackjack = new.dsc("BlackJack","BJ")
addScenario(dsc_blackjack,name="2DeckBJ",datamaker,args=list(decks=2,p=0.75,hands=100,deal=10),seed=1:1000)
addScenario(dsc_blackjack,name="6DeckBJ",datamaker,args=list(decks=6,p=0.75,hands=100,deal=10),seed=1:1000)
addScenario(dsc_blackjack,name="10DeckBJ",datamaker,args=list(decks=10,p=0.75,hands=100,deal=10),seed=1:1000)
addMethod(dsc_blackjack,name="SimpleSumThresh",fn = SimpleSum,args=list(Thresh=16, bet=1))
addMethod(dsc_blackjack,name="SimpleHitStand",fn = SimpleHS,args=list(bet=1))
addMethod(dsc_blackjack,name="SimpleHitStandDouble",fn = SimpleHSD,args=list(bet=1))
addMethod(dsc_blackjack,name="SimpleHitStandDoubleSplit",fn = SimpleHSDSp,args=list(bet=1))
addMethod(dsc_blackjack,name="SimpleHitStandDoubleSplit_HiLo",fn = SimpleHSDSpHL,args=list(bet=1))
addScore(dsc_blackjack,"basicscore",score)

res=run_dsc(dsc_blackjack)
summaryResults<-aggregate(WinningsPerBet ~ scenario + method, res, mean)


